#!/usr/bin/env bash

# This is located in root for use in Github Codespace
# https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-codespaces-for-your-account#dotfiles

echo "This does nothing at the moment. Sad face."
