# Icon set: https://www.nerdfonts.com/cheat-sheet

# Generic

export BEELINE_ICON_GENERIC_COMMENT=""
export BEELINE_ICON_GENERIC_USER=""
export BEELINE_ICON_GENERIC_SUPERUSER=""
export BEELINE_ICON_GENERIC_WINDOWS=""
export BEELINE_ICON_GENERIC_CLOCK=""
export BEELINE_ICON_GENERIC_STOPWATCH="祥"
export BEELINE_ICON_GENERIC_CALENDER=""
export BEELINE_ICON_GENERIC_NOTIFICATION=""
export BEELINE_ICON_GENERIC_CHAT=""
export BEELINE_ICON_GENERIC_GLOBE="爵"
export BEELINE_ICON_GENERIC_EMAIL="﫯"
export BEELINE_ICON_GENERIC_PLAYING=""
export BEELINE_ICON_GENERIC_PAUSED=""
export BEELINE_ICON_GENERIC_INCOGNITO=""
export BEELINE_ICON_GENERIC_SUCCESS=""
export BEELINE_ICON_GENERIC_ERROR=""
export BEELINE_ICON_GENERIC_WARNING=""
export BEELINE_ICON_GENERIC_LOADING=""

# Powerline icon set

export BEELINE_ICON_POWERLINE_R_LEADER=""
export BEELINE_ICON_POWERLINE_R_CAP=""
export BEELINE_ICON_POWERLINE_R_SOFT_SEP=""
export BEELINE_ICON_POWERLINE_R_HARD_SEP=""
export BEELINE_ICON_POWERLINE_L_LEADER=""
export BEELINE_ICON_POWERLINE_L_CAP=""
export BEELINE_ICON_POWERLINE_L_SOFT_SEP=""
export BEELINE_ICON_POWERLINE_L_HARD_SEP=""

# Supported operating systems

export BEELINE_ICON_OS_APPLE=""
export BEELINE_ICON_OS_WINDOWS=""
export BEELINE_ICON_OS_RPI=""
export BEELINE_ICON_OS_DEBIAN=""
export BEELINE_ICON_OS_ARCH=""
export BEELINE_ICON_OS_CENTOS=""
export BEELINE_ICON_OS_ALPINE=""
export BEELINE_ICON_OS_OPENSUSE=""
export BEELINE_ICON_OS_UBUNTU=""

# Git status symbols

export BEELINE_ICON_GIT_CLEAN=${BEELINE_ICON_GENERIC_SUCCESS}
export BEELINE_ICON_GIT_DIRTY="" # Likely being developed
export BEELINE_ICON_GIT_ACTIVE=${BEELINE_ICON_GENERIC_WARNING} # No unstaged changes, but gitignored files exist
export BEELINE_ICON_GIT_COMMIT=""
export BEELINE_ICON_GIT_TAG="笠"
export BEELINE_ICON_GIT_BEHIND=""
export BEELINE_ICON_GIT_AHEAD=""
export BEELINE_ICON_GIT_DIVERGED=""
export BEELINE_ICON_GIT_STAGED="●"
export BEELINE_ICON_GIT_MODIFIED=""
export BEELINE_ICON_GIT_UNTRACKED=""
export BEELINE_ICON_GIT_STASHED=""
export BEELINE_ICON_GIT_ISSUES=""
export BEELINE_ICON_GIT_PR=""
export BEELINE_ICON_GIT_DELETED=""
export BEELINE_ICON_GIT_CONFLICT="咽"
export BEELINE_ICON_GIT_RENAMED="凜"

# Events (for themeing prompt)

export BEELINE_ICON_EVENT_BRAILLE_DAY="" # 4 Jan
export BEELINE_ICON_EVENT_AUSTRALIA_DAY="" # 26 Jan
export BEELINE_ICON_EVENT_PI_DAY="" # 14 Mar
export BEELINE_ICON_EVENT_EARTH_DAY="" # 22 Apr
export BEELINE_ICON_EVENT_EASTER="✝" # Varies
export BEELINE_ICON_EVENT_STAR_WARS_DAY="" # 4 May
export BEELINE_ICON_EVENT_BEE_DAY="" # 20 May
export BEELINE_ICON_EVENT_RUOK_DAY="" # 8 Sep
export BEELINE_ICON_EVENT_WORLD_PEACE_DAY="" # 21 Sep
export BEELINE_ICON_EVENT_MENTAL_HEALTH_DAY="" # 10 Oct
export BEELINE_ICON_EVENT_HALLOWEEN="" # 31 Oct
export BEELINE_ICON_EVENT_CANDY_CANE="" # Dec
export BEELINE_ICON_EVENT_CHISTMAS_TREE="" # Dec
export BEELINE_ICON_EVENT_BOXING_DAY="" # Dec 26
export BEELINE_ICON_EVENT_QUEEN_BIRTHDAY=""
export BEELINE_ICON_EVENT_NYE="" # Dec 31
export BEELINE_ICON_EVENT_ELECTION=""
export BEELINE_ICON_EVENT_ROMANTIC=""
export BEELINE_ICON_EVENT_REMEMBERANCE=""
export BEELINE_ICON_EVENT_PUBLIC_HOLIDAY=""
export BEELINE_ICON_EVENT_BIRTHDAY=""
export BEELINE_ICON_EVENT_HAPPY_BIRTHDAY=""
# export BEELINE_ICON_EVENT_LUNAR_NEW_YEAR=""

# Brand logos

export BEELINE_ICON_BRAND_BITBUCKET=""
export BEELINE_ICON_BRAND_GITEA=""
export BEELINE_ICON_BRAND_GITHUB=""
export BEELINE_ICON_BRAND_GIT=""

# Special directories

export BEELINE_ICON_DIR_GENERIC=""
export BEELINE_ICON_DIR_HOME=""
export BEELINE_ICON_DIR_XDG_CONFIG=""
export BEELINE_ICON_DIR_XDG_DOTFILE=""
export BEELINE_ICON_DIR_XDG_REPOS=''
export BEELINE_ICON_DIR_SYNC_ROOT="מּ"
export BEELINE_ICON_DIR_SYNC_ARCHIVE=""
export BEELINE_ICON_DIR_SYNC_CLIENTS=""
export BEELINE_ICON_DIR_SYNC_INBOX=""
export BEELINE_ICON_DIR_SYNC_LIBRARY=""
# export BEELINE_ICON_DIR_SYNC_MEDIA=""
export BEELINE_ICON_DIR_SYNC_GAMES=""
export BEELINE_ICON_DIR_SYNC_LITERATURE=""
export BEELINE_ICON_DIR_SYNC_MUSIC=""
export BEELINE_ICON_DIR_SYNC_PHOTOS=""
export BEELINE_ICON_DIR_SYNC_RECORDINGS=""
export BEELINE_ICON_DIR_SYNC_VIDEOS=""
export BEELINE_ICON_DIR_SYNC_PERSONAL=""
export BEELINE_ICON_DIR_SYNC_VAULT=""
export BEELINE_ICON_DIR_SYNC_SHARED=""
export BEELINE_ICON_DIR_VOLUME=""
export BEELINE_ICON_DIR_EXTERNAL="禍"
export BEELINE_ICON_DIR_NETWORK="歷"
export BEELINE_ICON_DIR_ROOT=""

# Weather

export BEELINE_ICON_WEATHER_RAIN="歹"
export BEELINE_ICON_WEATHER_SPRINKLE=""
export BEELINE_ICON_WEATHER_STORM="ﭼ"
export BEELINE_ICON_WEATHER_CLOUDY=""
export BEELINE_ICON_WEATHER_OVERCAST_DAY="杖"
export BEELINE_ICON_WEATHER_OVERCAST_NIGHT=""
export BEELINE_ICON_WEATHER_NIGHT="望"
export BEELINE_ICON_WEATHER_SUNNY=""
export BEELINE_ICON_WEATHER_TEMP=""
export BEELINE_ICON_WEATHER_UNDEFINED=""
export BEELINE_ICON_WEATHER_SNOW=$BEELINE_ICON_WEATHER_UNDEFINED # We don't get snow 😂

# Time keeping

export BEELINE_ICON_TIME_1=""
export BEELINE_ICON_TIME_2=""
export BEELINE_ICON_TIME_3=""
export BEELINE_ICON_TIME_4=""
export BEELINE_ICON_TIME_5=""
export BEELINE_ICON_TIME_6=""
export BEELINE_ICON_TIME_7=""
export BEELINE_ICON_TIME_8=""
export BEELINE_ICON_TIME_9=""
export BEELINE_ICON_TIME_10=""
export BEELINE_ICON_TIME_11=""
export BEELINE_ICON_TIME_12=""
export BEELINE_ICON_TIME_AM="ᴬᴹ"
export BEELINE_ICON_TIME_PM="ₚₘ"
